semantic
DzmitryKosmach/DzmitryKosmach.github.io pull request #2
Opened 2017-03-27 17:07 UTC by DzmitryKosmach

2017-03-27 18:18 UTC, NikitaSedyx requested changes

2017-03-27 18:18 UTC, NikitaSedyx commented on style/main.css
> +}
nit: empty line

2017-03-27 18:18 UTC, NikitaSedyx commented on index.html
> +    <script src="js/main.js" type="text/javascript"></script>
have you removed main.js?

2017-03-27 18:18 UTC, NikitaSedyx commented on index.html
> +        <main>
main is unique tag in document

2017-03-27 18:18 UTC, NikitaSedyx commented on index.html
> +        <aside></aside>
imo aside should be outside section, you will have a problem with css with this structure

2017-03-28 08:16 UTC, DzmitryKosmach commented
https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/2


2017-03-27 21:18 GMT+03:00 Mikita Siadykh <notifications@github.com>:

> *@NikitaSedyx* requested changes on this pull request.
> ------------------------------
>
> In style/main.css
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/2#discussion_r108241234>
> :
>
> > +section:nth-child(even) {	
> +	float:right;
> +}
> +
> +section header, section footer{
> +	text-align:center;
> +        font-size: 1.5em;
> +}
> +
> +section main figure{
> +	width: 128px;
> +	float:left;}
> +	
> +.clear {
> +	clear:both;
> +}
>
> nit: empty line
> ------------------------------
>
> In index.html
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/2#discussion_r108241366>
> :
>
> > @@ -1,9 +1,76 @@
>  <html>
> -    <head>
> -        <title>Hello</title>
> -        <script src="js/main.js" type="text/javascript"></script>
> -    </head>
> -    <body>
> -        <div>Hello</div>
> -    </body>
> +  <head>
> +    <title>Semantic elements</title>
> +    <link href="style/main.css" rel="stylesheet" type="text/css"/>
> +    <script src="js/main.js" type="text/javascript"></script>
>
> have you removed main.js?
> ------------------------------
>
> In index.html
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/2#discussion_r108241713>
> :
>
> > +      <div id="logo"><a href="#">&reg;</a></div>
> +      <nav>
> +        <ul>
> +          <li><a href="#">Main</a></li>
> +          <li><a href="#">About</a></li>
> +          <li><a href="#">Other</a></li>
> +          <li><a href="#">Links</a></li>
> +        </ul>
> +      </nav>
> +      <div class="clear"></div>
> +    </header>
> +    <main id="main">
> +      <h1>Main</h1>
> +      <section>
> +        <header>Header</header>
> +        <main>
>
> main is unique tag in document
> ------------------------------
>
> In index.html
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/2#discussion_r108241988>
> :
>
> > +            </figcaption>
> +          </figure>
> +          <p><mark>Lorem Ipsum</mark> is simply dummy text of the printing and typesetting
> +              industry. Lorem Ipsum has been the industry's standard dummy text
> +              ever since the 1500s, when an unknown printer took a galley of
> +              type and scrambled it to make a type specimen book. It has
> +              survived not only five centuries, but also the leap into
> +              electronic typesetting, remaining essentially unchanged. It was
> +              popularised in the 1960s with the release of Letraset sheets
> +              containing Lorem Ipsum passages, and more recently with desktop
> +              publishing software like Aldus PageMaker including versions of
> +              Lorem Ipsum.
> +            </p>
> +        </main>
> +        <footer>Footer</footer>
> +        <aside></aside>
>
> imo aside should be outside section, you will have a problem with css with
> this structure
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/2#pullrequestreview-29260552>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXTurovEOhG24T84009U14BhlwHM6UWXks5rp_2NgaJpZM4Mqjhc>
> .
>

2017-04-01 12:59 UTC, NikitaSedyx approved these changes

2017-04-01 13:00 UTC, NikitaSedyx approved these changes

2017-04-01 13:35 UTC, merged