arrays
DzmitryKosmach/DzmitryKosmach.github.io pull request #4
Opened 2017-04-06 19:54 UTC by DzmitryKosmach

2017-04-12 04:44 UTC, NikitaSedyx requested changes

2017-04-12 04:44 UTC, NikitaSedyx commented on task_arrays/index.html
> +</html>
nit: empty line at the eof

2017-04-12 04:44 UTC, NikitaSedyx commented on task_arrays/js/main.js
> +}
same

2017-04-12 04:44 UTC, NikitaSedyx commented on task_arrays/js/main.js
> +    array.length -= exclude;
you should remember, it mutates array, -1

2017-04-12 04:44 UTC, NikitaSedyx commented on task_arrays/js/main.js
> +  array.forEach(function () {
what is the problem to add function arguments instead of usage `arguments`

2017-04-12 04:44 UTC, NikitaSedyx commented on task_arrays/js/main.js
> +    if (!!array[i]) {
what do you think will `if (array[i])` work without `!!`? ad why

2017-04-12 04:44 UTC, NikitaSedyx commented on task_arrays/js/main.js
> +function range() {
next cases should work:
range(10) [0..9]
range(1, 10) [1..9]
range(1, 10, 3) [1, 4, 7]
range(10, null, 3) [0, 3, 6, 9]
range(10, null) the same with range(10)
range(-2, -5) []
range(-5, -2) [-5, -4, -3]
range(-5, -2, 2) [-5, -3]
range(-5, -2, -2) []
range(-5, null, 2) []
range(-5, null, -2) [0, -2, -4]
range(-10, -20, -5) [-10, -15]
range(-20, -10, -5) []

FYI this function can be implemented ~10 lines, firstly you should find step and length of result array (the difficult part of this function)

2017-04-12 04:44 UTC, NikitaSedyx commented on task_arrays/js/main.js
> +function range() {
where are you function arguments?

2017-04-15 16:00 UTC, DzmitryKosmach commented
https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/4/commits/3d570767986f7ea9c410466d28864d4328ed2c6f


2017-04-12 7:44 GMT+03:00 Mikita Siadykh <notifications@github.com>:

> *@NikitaSedyx* requested changes on this pull request.
> ------------------------------
>
> In task_arrays/index.html
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/4#discussion_r111063855>
> :
>
> > @@ -0,0 +1,9 @@
> +<html>
> +  <head>
> +    <title>Arrays</title>
> +    <script src="js/main.js" type="text/javascript"></script>
> +  </head>
> +  <body>
> +    Arrays
> +  </body>
> +</html>
>
> nit: empty line at the eof
> ------------------------------
>
> In task_arrays/js/main.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/4#discussion_r111063878>
> :
>
> > +    })) {
> +      uniqueArray.push(array[index]);
> +    }
> +  });
> +  return uniqueArray;
> +}
> +
> +function last(array) {
> +  return array[array.length - 1];
> +}
> +
> +function excludeLast(array, exclude = 1) {
> +  if (exclude > 0) {
> +    array.length -= exclude;
> +  }
> +}
>
> same
> ------------------------------
>
> In task_arrays/js/main.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/4#discussion_r111063906>
> :
>
> > +    if (uniqueArray.every(function (item) {
> +      return !(item === array[index]);
> +    })) {
> +      uniqueArray.push(array[index]);
> +    }
> +  });
> +  return uniqueArray;
> +}
> +
> +function last(array) {
> +  return array[array.length - 1];
> +}
> +
> +function excludeLast(array, exclude = 1) {
> +  if (exclude > 0) {
> +    array.length -= exclude;
>
> you should remember, it mutates array, -1
> ------------------------------
>
> In task_arrays/js/main.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/4#discussion_r111064081>
> :
>
> > +  var result = 0;
> +  for (var i = 0; i < array.length; i++) {
> +    result += array[i];
> +  }
> +  return result;
> +}
> +
> +function sumReduce(array) {
> +  return array.reduce(function (sum, current) {
> +    return sum + current;
> +  });
> +}
> +
> +function unique(array) {
> +  var uniqueArray = [];
> +  array.forEach(function () {
>
> what is the problem to add function arguments instead of usage arguments
> ------------------------------
>
> In task_arrays/js/main.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/4#discussion_r111064128>
> :
>
> > +  if (arguments[1]) {
> +    endValue = arguments[1];
> +    startValue = arguments[0];
> +  } else {
> +    endValue = arguments[0];
> +  }
> +  for (var i = startValue; i < endValue; i += stepValue) {
> +    array.push(i);
> +  }
> +  return array;
> +}
> +
> +function compactFor(array) {
> +  var compactArray = [];
> +  for (var i = 0; i < array.length; i++) {
> +    if (!!array[i]) {
>
> what do you think will if (array[i]) work without !!? ad why
> ------------------------------
>
> In task_arrays/js/main.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/4#discussion_r111064224>
> :
>
> > +
> +function isArrayInstanceof(arg) {
> +  if (!isObject(arg)) {
> +    return false;
> +  }
> +  return arg instanceof Array;
> +}
> +
> +function isObject(arg) {
> +  if (arg === null) {
> +    return false;
> +  }
> +  return typeof arg === 'object';
> +}
> +
> +function range() {
>
> next cases should work:
> range(10) [0..9]
> range(1, 10) [1..9]
> range(1, 10, 3) [1, 4, 7]
> range(10, null, 3) [0, 3, 6, 9]
> range(10, null) the same with range(10)
> range(-2, -5) []
> range(-5, -2) [-5, -4, -3]
> range(-5, -2, 2) [-5, -3]
> range(-5, -2, -2) []
> range(-5, null, 2) []
> range(-5, null, -2) [0, -2, -4]
> range(-10, -20, -5) [-10, -15]
> range(-20, -10, -5) []
>
> FYI this function can be implemented ~10 lines, firstly you should find
> step and length of result array (the difficult part of this function)
> ------------------------------
>
> In task_arrays/js/main.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/4#discussion_r111064237>
> :
>
> > +
> +function isArrayInstanceof(arg) {
> +  if (!isObject(arg)) {
> +    return false;
> +  }
> +  return arg instanceof Array;
> +}
> +
> +function isObject(arg) {
> +  if (arg === null) {
> +    return false;
> +  }
> +  return typeof arg === 'object';
> +}
> +
> +function range() {
>
> where are you function arguments?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/4#pullrequestreview-32280563>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXTurubKc9kcFeKVHye4BEIgUhaIuLkZks5rvFaagaJpZM4M2Fw_>
> .
>

2017-04-17 12:45 UTC, NikitaSedyx approved these changes
mostly lgtm

2017-04-17 12:45 UTC, NikitaSedyx commented on task_arrays/js/main.js
> +    if (uniqueArray.every(function (item) {
I'd suggest to move `every` outside of `if` to better readability

2017-04-17 17:19 UTC, merged