ajax
DzmitryKosmach/DzmitryKosmach.github.io pull request #6
Opened 2017-05-02 07:04 UTC by DzmitryKosmach

2017-05-02 16:51 UTC, NikitaSedyx requested changes
you will have problems with this approach when you start drawing the data

2017-05-02 16:51 UTC, NikitaSedyx commented on task_ajax/js/app.js
> +new LastFmRequest("artist.search", "cher" , null ,API_KEY, format);
codestyle

2017-05-02 16:51 UTC, NikitaSedyx commented on task_ajax/js/classes/lastFmRequest.class.js
> +  this.load(new QueryParams("GET", url + method + artist + album + apiKey + format));
why constructor loads data?

2017-05-02 16:51 UTC, NikitaSedyx commented on task_ajax/js/classes/lastFmRequest.class.js
> +  this.load(new QueryParams("GET", url + method + artist + album + apiKey + format));
what about encoding?

2017-05-03 07:59 UTC, DzmitryKosmach commented
Last.fm fixed:

https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6/commits/db47326c6ea9f327c63edbe06c0f7b70d1d62a7c


2017-05-02 19:51 GMT+03:00 Mikita Siadykh <notifications@github.com>:

> *@NikitaSedyx* requested changes on this pull request.
>
> you will have problems with this approach when you start drawing the data
> ------------------------------
>
> In task_ajax/js/app.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r114366989>
> :
>
> > @@ -0,0 +1,8 @@
> +"use strict";
> +
> +var API_KEY = "61d6600170ff0cf825a3ee62d4bd7fa6";
> +var format = "json";
> +new LastFmRequest("chart.gettopartists", null , null, API_KEY, format);
> +new LastFmRequest("artist.search", "cher" , null ,API_KEY, format);
>
> codestyle
> ------------------------------
>
> In task_ajax/js/classes/lastFmRequest.class.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r114367408>
> :
>
> > @@ -0,0 +1,20 @@
> +function LastFmRequest(method, artist, album, api_key, format) {
> +  var url = "http://ws.audioscrobbler.com/2.0";
> +  var method = method ? "/?method=" + method : "";
> +  var artist = artist ? "&artist=" + artist : "";
> +  var album = album ? "&album=" + album : "";
> +  var apiKey = api_key ? "&api_key=" + api_key : "";
> +  var format = format ? "&format=" + format : "";
> +  this.load(new QueryParams("GET", url + method + artist + album + apiKey + format));
>
> why constructor loads data?
> ------------------------------
>
> In task_ajax/js/classes/lastFmRequest.class.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r114367537>
> :
>
> > @@ -0,0 +1,20 @@
> +function LastFmRequest(method, artist, album, api_key, format) {
> +  var url = "http://ws.audioscrobbler.com/2.0";
> +  var method = method ? "/?method=" + method : "";
> +  var artist = artist ? "&artist=" + artist : "";
> +  var album = album ? "&album=" + album : "";
> +  var apiKey = api_key ? "&api_key=" + api_key : "";
> +  var format = format ? "&format=" + format : "";
> +  this.load(new QueryParams("GET", url + method + artist + album + apiKey + format));
>
> what about encoding?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#pullrequestreview-35826871>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXTurh1QzoRyGVGp2l22PgB-FQCzbZ1cks5r118UgaJpZM4NNx_n>
> .
>

2017-05-05 16:21 UTC, NikitaSedyx requested changes

2017-05-05 16:21 UTC, NikitaSedyx commented on task_ajax/js/classes/albumGetInfo.class.js
> +function AlbumGetInfo(artist, album, api_key) {
why artist and album are instance fields? they should be arguments for load function, don't you think so?
you no need to create new instance when you want to load data with another parameters

2017-05-05 16:21 UTC, NikitaSedyx commented on task_ajax/js/app.js
> +var apiKey = "61d6600170ff0cf825a3ee62d4bd7fa6";
imo it's common parameter

2017-05-05 16:21 UTC, NikitaSedyx commented on task_ajax/js/classes/lastFmRequest.class.js
> +  this.queryParams = url + reguestMethod + artist + album + apiKey + format;
queryParams requires encodind

2017-05-05 16:21 UTC, NikitaSedyx commented on task_ajax/js/app.js
> +var apiKey = "61d6600170ff0cf825a3ee62d4bd7fa6";
static field of LastFmRequest

2017-05-05 20:31 UTC, DzmitryKosmach commented
Please explain the remark:

queryParams requires encodind

In task_ajax/js/classes/lastFmRequest.class.js
<https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035751>
:

> @@ -0,0 +1,24 @@
+function LastFmRequest(reguestMethod, artist, album, api_key) {
+  var url = "http://ws.audioscrobbler.com/2.0";
+  var reguestMethod = reguestMethod ? "/?method=" + reguestMethod : "";
+  var artist = artist ? "&artist=" + artist : "";
+  var album = album ? "&album=" + album : "";
+  var apiKey = api_key ? "&api_key=" + api_key : "";
+  var format = "&format=json";
+  this.queryParams = url + reguestMethod + artist + album + apiKey + format;



2017-05-05 19:21 GMT+03:00 Mikita Siadykh <notifications@github.com>:

> *@NikitaSedyx* requested changes on this pull request.
> ------------------------------
>
> In task_ajax/js/classes/albumGetInfo.class.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035571>
> :
>
> > @@ -0,0 +1,12 @@
> +function AlbumGetInfo(artist, album, api_key) {
>
> why artist and album are instance fields? they should be arguments for
> load function, don't you think so?
> you no need to create new instance when you want to load data with another
> parameters
> ------------------------------
>
> In task_ajax/js/app.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035631>
> :
>
> > @@ -0,0 +1,7 @@
> +"use strict";
> +
> +var apiKey = "61d6600170ff0cf825a3ee62d4bd7fa6";
>
> imo it's common parameter
> ------------------------------
>
> In task_ajax/js/classes/lastFmRequest.class.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035751>
> :
>
> > @@ -0,0 +1,24 @@
> +function LastFmRequest(reguestMethod, artist, album, api_key) {
> +  var url = "http://ws.audioscrobbler.com/2.0";
> +  var reguestMethod = reguestMethod ? "/?method=" + reguestMethod : "";
> +  var artist = artist ? "&artist=" + artist : "";
> +  var album = album ? "&album=" + album : "";
> +  var apiKey = api_key ? "&api_key=" + api_key : "";
> +  var format = "&format=json";
> +  this.queryParams = url + reguestMethod + artist + album + apiKey + format;
>
> queryParams requires encodind
> ------------------------------
>
> In task_ajax/js/app.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035907>
> :
>
> > @@ -0,0 +1,7 @@
> +"use strict";
> +
> +var apiKey = "61d6600170ff0cf825a3ee62d4bd7fa6";
>
> static field of LastFmRequest
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#pullrequestreview-36550297>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXTurppF10lGsZdq1tU6SpZ2FM1MRtqxks5r20yUgaJpZM4NNx_n>
> .
>

2017-05-10 20:36 UTC, DzmitryKosmach commented
Last.fm fixed:

https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6/commits/749cab31309c2c1b88b8d117fe87faaacd151d06


2017-05-05 23:31 GMT+03:00 Dzmitry Kosmach <dzmitry.kosmach@gmail.com>:

> Please explain the remark:
>
> queryParams requires encodind
>
> In task_ajax/js/classes/lastFmRequest.class.js
> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035751>
> :
>
> > @@ -0,0 +1,24 @@
> +function LastFmRequest(reguestMethod, artist, album, api_key) {
> +  var url = "http://ws.audioscrobbler.com/2.0";
> +  var reguestMethod = reguestMethod ? "/?method=" + reguestMethod : "";
> +  var artist = artist ? "&artist=" + artist : "";
> +  var album = album ? "&album=" + album : "";
> +  var apiKey = api_key ? "&api_key=" + api_key : "";
> +  var format = "&format=json";
> +  this.queryParams = url + reguestMethod + artist + album + apiKey + format;
>
>
>
> 2017-05-05 19:21 GMT+03:00 Mikita Siadykh <notifications@github.com>:
>
>> *@NikitaSedyx* requested changes on this pull request.
>> ------------------------------
>>
>> In task_ajax/js/classes/albumGetInfo.class.js
>> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035571>
>> :
>>
>> > @@ -0,0 +1,12 @@
>> +function AlbumGetInfo(artist, album, api_key) {
>>
>> why artist and album are instance fields? they should be arguments for
>> load function, don't you think so?
>> you no need to create new instance when you want to load data with
>> another parameters
>> ------------------------------
>>
>> In task_ajax/js/app.js
>> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035631>
>> :
>>
>> > @@ -0,0 +1,7 @@
>> +"use strict";
>> +
>> +var apiKey = "61d6600170ff0cf825a3ee62d4bd7fa6";
>>
>> imo it's common parameter
>> ------------------------------
>>
>> In task_ajax/js/classes/lastFmRequest.class.js
>> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035751>
>> :
>>
>> > @@ -0,0 +1,24 @@
>> +function LastFmRequest(reguestMethod, artist, album, api_key) {
>> +  var url = "http://ws.audioscrobbler.com/2.0";
>> +  var reguestMethod = reguestMethod ? "/?method=" + reguestMethod : "";
>> +  var artist = artist ? "&artist=" + artist : "";
>> +  var album = album ? "&album=" + album : "";
>> +  var apiKey = api_key ? "&api_key=" + api_key : "";
>> +  var format = "&format=json";
>> +  this.queryParams = url + reguestMethod + artist + album + apiKey + format;
>>
>> queryParams requires encodind
>> ------------------------------
>>
>> In task_ajax/js/app.js
>> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#discussion_r115035907>
>> :
>>
>> > @@ -0,0 +1,7 @@
>> +"use strict";
>> +
>> +var apiKey = "61d6600170ff0cf825a3ee62d4bd7fa6";
>>
>> static field of LastFmRequest
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/6#pullrequestreview-36550297>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AXTurppF10lGsZdq1tU6SpZ2FM1MRtqxks5r20yUgaJpZM4NNx_n>
>> .
>>
>
>

2017-05-11 18:57 UTC, NikitaSedyx approved these changes

2017-05-12 07:44 UTC, merged